# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1367421870);
user_pref("app.update.lastUpdateTime.background-update-timer", 1367421750);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1367421990);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1367421445);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1367421565);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 9);
user_pref("browser.pagethumbnails.storage_version", 2);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage_override.buildID", "20130326150557");
user_pref("browser.startup.homepage_override.mstone", "20.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"addons\":4}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1367507845000");
user_pref("datareporting.policy.firstRunTime", "1367421445000");
user_pref("datareporting.sessions.current.activeTicks", 5);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1246);
user_pref("datareporting.sessions.current.main", 89);
user_pref("datareporting.sessions.current.sessionRestored", 1278);
user_pref("datareporting.sessions.current.startTime", "1367421629586");
user_pref("datareporting.sessions.current.totalTime", 1567002);
user_pref("datareporting.sessions.currentIndex", 1);
user_pref("datareporting.sessions.previous.0", "{\"s\":1367421444475,\"a\":18,\"t\":179202,\"c\":true,\"m\":94,\"fp\":1955,\"sr\":2067}");
user_pref("dom.mozApps.used", true);
user_pref("dom.w3c_touch_events.expose", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"garg_sms@yahoo.in\":{\"version\":\"1.1\",\"type\":\"extension\",\"descriptor\":\"/Users/adam/work/saunter/py.saunter-examples/picpaste/rc/support/profiles/red/extensions/garg_sms@yahoo.in.xpi\"}}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:20.0");
user_pref("extensions.installCache", "[{\"name\":\"app-system-local\",\"addons\":{\"{23fcfd51-4958-4f00-80a3-ae97e717ed8b}\":{\"descriptor\":\"/Library/Application Support/Mozilla/Extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{23fcfd51-4958-4f00-80a3-ae97e717ed8b}\",\"mtime\":1362284899000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/Applications/Firefox.app/Contents/MacOS/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1365430677000}}},{\"name\":\"app-profile\",\"addons\":{\"garg_sms@yahoo.in\":{\"descriptor\":\"/Users/adam/work/saunter/py.saunter-examples/picpaste/rc/support/profiles/red/extensions/garg_sms@yahoo.in.xpi\",\"mtime\":1367421499000}}}]");
user_pref("extensions.lastAppVersion", "20.0");
user_pref("extensions.lastPlatformVersion", "20.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20130326150557");
user_pref("gecko.mstone", "20.0");
user_pref("gfx.blacklist.webgl.msaa", 4);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 100664);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.startup.last_success", 1367421629);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1370013451);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
